# Generated by Django 4.1.1 on 2022-09-10 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("builder_app", "0002_tableinfo_delete_table_info"),
    ]

    operations = [
        migrations.RemoveField(model_name="tableinfo", name="user",),
    ]
