# Generated by Django 4.1.1 on 2022-09-11 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("builder_app", "0005_alter_tableinfo_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tableinfo",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="values",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
